In [1]:
#Script to reformat methane data Top-Down file for two-level Sankey
#In TD approach, Sources = regions, Targets = methane sources

#Output: json file formatted for Sankey diagram

#Created:       30.05.2016
#Last modified: 31.05.2016 Read in orig file (no manual reformatting necessary)
#               02.06.2016 New data files from Marielle Saunois; remove GLO category from final file
#               06.06.2016 Output json files (Sankey format) with min and max values, respectively
#               07.06.2016 Min/max values output only when mean != -99 or != 0
#               10.06.2016 New data files from Marielle
#               05.04.2020 Updated data files from Marielle
#               11.05.2020 Updated data files 2mai2020 from Marielle
#               13.05.2020 Updated data files 11mai2020 from Marielle

In [2]:
import numpy as np
import pandas as pd
import collections
import os

In [3]:
mydir = '../../../Documents/PROJECTS/METHANE_BUDGET/2020/data/'

data_date='11mai'

# Data file
fname=mydir + 'Sankey_TD_2008-2017_' + data_date + '2020.txt'

# Output files
mean_name = '../data/Sankey_TD_2008-2017_' + data_date + '2020_mean_2levels.json'
min_name = '../data/Sankey_TD_2008-2017_' + data_date + '2020_min_2levels.json'
max_name = '../data/Sankey_TD_2008-2017_' + data_date + '2020_max_2levels.json'

In [4]:
# Read data file

df_TD = pd.read_csv(fname, header=1, delim_whitespace=True)
df_TD

,proc,USA,Canada,Central_America,Northern_South_America,Brazil,Southwest_South_America,Europe,Northern_Africa,Equatorial_Africa,Southern_Africa,Russia,Central_Asia,Middle_East,China,Korean_Japan,South_Asia,Southeast_Asia,Oceania,GLO
Wetlands,mean,14,13,3,10,34,14,3,7,20,6,12,0,1,5,1,12,22,2,181
Wetlands,min,8,6,2,6,26,8,2,4,15,2,9,0,0,2,0,6,15,1,159
Wetlands,max,25,20,3,14,44,21,8,11,27,9,16,0,1,9,2,18,33,4,200
OtherNatural,mean,2,1,1,1,3,1,2,2,3,2,2,1,3,1,0,1,3,2,37
OtherNatural,min,1,0,1,1,1,1,1,1,1,0,1,0,1,1,0,1,1,1,21
OtherNatural,max,3,2,1,2,5,2,3,4,7,3,3,1,6,1,0,2,4,3,50
AgriWaste,mean,19,3,7,4,19,8,18,10,10,4,5,4,7,26,2,36,21,5,217
AgriWaste,min,10,2,5,3,11,6,13,10,6,4,4,3,5,23,2,24,20,3,207
AgriWaste,max,26,4,7,6,26,12,26,14,12,6,7,5,10,35,3,51,27,7,240
Fossil,mean,12,2,2,3,2,2,7,5,6,3,13,5,13,18,1,4,8,2,111
Fossil,min,9,1,1,2,1,1,3,3,2,2,4,3,3,10,0,2,5,1,81
Fossil,max,18,4,3,5,2,3,10,9,11,5,25,9,20,36,1,5,9,2,131
BioBurBiof,mean,1,1,1,0,2,1,1,2,5,3,2,0,0,4,0,2,5,1,30
BioBurBiof,min,0,1,0,0,1,1,1,1,4,2,2,0,0,0,0,2,4,0,22
BioBurBiof,max,1,1,1,0,3,1,1,2,6,3,3,0,0,5,0,3,7,1,36
SumSources,mean,47,20,13,20,60,26,31,26,44,18,34,10,23,55,4,56,59,12,576
SumSources,min,34,13,9,14,38,14,19,9,31,12,17,7,15,43,3,26,46,8,550
SumSources,max,62,30,28,27,78,35,41,34,60,24,47,15,31,70,5,73,67,24,594

In [5]:
df_TD.rename(columns = {'proc':'stats'}, inplace = True)
df_TD.index.name = 'proc'
df_TD

,stats,USA,Canada,Central_America,Northern_South_America,Brazil,Southwest_South_America,Europe,Northern_Africa,Equatorial_Africa,Southern_Africa,Russia,Central_Asia,Middle_East,China,Korean_Japan,South_Asia,Southeast_Asia,Oceania,GLO
proc,,,,,,,,,,,,,,,,,,,,
Wetlands,mean,14,13,3,10,34,14,3,7,20,6,12,0,1,5,1,12,22,2,181
Wetlands,min,8,6,2,6,26,8,2,4,15,2,9,0,0,2,0,6,15,1,159
Wetlands,max,25,20,3,14,44,21,8,11,27,9,16,0,1,9,2,18,33,4,200
OtherNatural,mean,2,1,1,1,3,1,2,2,3,2,2,1,3,1,0,1,3,2,37
OtherNatural,min,1,0,1,1,1,1,1,1,1,0,1,0,1,1,0,1,1,1,21
OtherNatural,max,3,2,1,2,5,2,3,4,7,3,3,1,6,1,0,2,4,3,50
AgriWaste,mean,19,3,7,4,19,8,18,10,10,4,5,4,7,26,2,36,21,5,217
AgriWaste,min,10,2,5,3,11,6,13,10,6,4,4,3,5,23,2,24,20,3,207
AgriWaste,max,26,4,7,6,26,12,26,14,12,6,7,5,10,35,3,51,27,7,240
Fossil,mean,12,2,2,3,2,2,7,5,6,3,13,5,13,18,1,4,8,2,111
Fossil,min,9,1,1,2,1,1,3,3,2,2,4,3,3,10,0,2,5,1,81
Fossil,max,18,4,3,5,2,3,10,9,11,5,25,9,20,36,1,5,9,2,131
BioBurBiof,mean,1,1,1,0,2,1,1,2,5,3,2,0,0,4,0,2,5,1,30
BioBurBiof,min,0,1,0,0,1,1,1,1,4,2,2,0,0,0,0,2,4,0,22
BioBurBiof,max,1,1,1,0,3,1,1,2,6,3,3,0,0,5,0,3,7,1,36
SumSources,mean,47,20,13,20,60,26,31,26,44,18,34,10,23,55,4,56,59,12,576
SumSources,min,34,13,9,14,38,14,19,9,31,12,17,7,15,43,3,26,46,8,550
SumSources,max,62,30,28,27,78,35,41,34,60,24,47,15,31,70,5,73,67,24,594

In [6]:
#Pivot table so that "stats" Mean, Min, Max become three columns under each region column
#and "proc" becomes index
df_TD_piv = df_TD.pivot(columns='stats', index=df_TD.index)
df_TD_piv

             USA          Canada          Central_America           \
stats        max mean min    max mean min             max mean min
proc
AgriWaste     26   19  10      4    3   2               7    7   5
BioBurBiof     1    1   0      1    1   1               1    1   0
Fossil        18   12   9      4    2   1               3    2   1
OtherNatural   3    2   1      2    1   0               1    1   1
SumSources    62   47  34     30   20  13              28   13   9
Wetlands      25   14   8     20   13   6               3    3   2

             Northern_South_America  ... South_Asia Southeast_Asia           \
stats                           max  ...        min            max mean min
proc                                 ...
AgriWaste                         6  ...         24             27   21  20
BioBurBiof                        0  ...          2              7    5   4
Fossil                            5  ...          2              9    8   5
OtherNatural                      2  ...          1              4    3   1
SumSources                       27  ...         26             67   59  46
Wetlands                         14  ...          6             33   22  15

             Oceania           GLO
stats            max mean min  max mean  min
proc
AgriWaste          7    5   3  240  217  207
BioBurBiof         1    1   0   36   30   22
Fossil             2    2   1  131  111   81
OtherNatural       3    2   1   50   37   21
SumSources        24   12   8  594  576  550
Wetlands           4    2   1  200  181  159

[6 rows x 57 columns]

In [7]:
df_TD_piv.columns[0][0]

'USA'

In [8]:
df_TD_piv.columns[0][0] #Bor_NAme
df_TD_piv.columns[3][0] #contUSA
df_TD_piv.columns[6][0] #CentName
df_TD_piv.columns[9][0] #Trop_SAme

'Northern_South_America'

In [9]:
list(df_TD)

['stats',
 'USA',
 'Canada',
 'Central_America',
 'Northern_South_America',
 'Brazil',
 'Southwest_South_America',
 'Europe',
 'Northern_Africa',
 'Equatorial_Africa',
 'Southern_Africa',
 'Russia',
 'Central_Asia',
 'Middle_East',
 'China',
 'Korean_Japan',
 'South_Asia',
 'Southeast_Asia',
 'Oceania',
 'GLO']

In [10]:
df_TD_piv['Canada']['mean']

proc
AgriWaste        3
BioBurBiof       1
Fossil           2
OtherNatural     1
SumSources      20
Wetlands        13
Name: mean, dtype: int64

In [11]:
df_TD_piv['Canada'].loc['AgriWaste']['mean']

3

In [12]:
df_TD_piv['Canada'].loc['BioBurBiof']['mean']

1

In [13]:
print(df_TD_piv.shape)
df_TD_piv

(6, 57)

             USA          Canada          Central_America           \
stats        max mean min    max mean min             max mean min
proc
AgriWaste     26   19  10      4    3   2               7    7   5
BioBurBiof     1    1   0      1    1   1               1    1   0
Fossil        18   12   9      4    2   1               3    2   1
OtherNatural   3    2   1      2    1   0               1    1   1
SumSources    62   47  34     30   20  13              28   13   9
Wetlands      25   14   8     20   13   6               3    3   2

             Northern_South_America  ... South_Asia Southeast_Asia           \
stats                           max  ...        min            max mean min
proc                                 ...
AgriWaste                         6  ...         24             27   21  20
BioBurBiof                        0  ...          2              7    5   4
Fossil                            5  ...          2              9    8   5
OtherNatural                      2  ...          1              4    3   1
SumSources                       27  ...         26             67   59  46
Wetlands                         14  ...          6             33   22  15

             Oceania           GLO
stats            max mean min  max mean  min
proc
AgriWaste          7    5   3  240  217  207
BioBurBiof         1    1   0   36   30   22
Fossil             2    2   1  131  111   81
OtherNatural       3    2   1   50   37   21
SumSources        24   12   8  594  576  550
Wetlands           4    2   1  200  181  159

[6 rows x 57 columns]

In [14]:
#Store region names in list
regions = list(df_TD)
if 'stats' in regions: regions.remove('stats')
if 'GLO' in regions: regions.remove('GLO')
numRegions = len(regions)

idx = 0
sources = []
for num in range(0,numRegions):
    print(num)
    sources.append(df_TD_piv.columns[idx][0])
    idx = idx + 3
   
print(sources)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
['USA', 'Canada', 'Central_America', 'Northern_South_America', 'Brazil', 'Southwest_South_America', 'Europe', 'Northern_Africa', 'Equatorial_Africa', 'Southern_Africa', 'Russia', 'Central_Asia', 'Middle_East', 'China', 'Korean_Japan', 'South_Asia', 'Southeast_Asia', 'Oceania']

In [15]:
#Get target list
targets = df_TD_piv.index.tolist()
targets

['AgriWaste', 'BioBurBiof', 'Fossil', 'OtherNatural', 'SumSources', 'Wetlands']

In [16]:
if 'SumSources' in targets: targets.remove('SumSources')
targets

['AgriWaste', 'BioBurBiof', 'Fossil', 'OtherNatural', 'Wetlands']

In [17]:
nodes = sources + targets
nodes

['USA',
 'Canada',
 'Central_America',
 'Northern_South_America',
 'Brazil',
 'Southwest_South_America',
 'Europe',
 'Northern_Africa',
 'Equatorial_Africa',
 'Southern_Africa',
 'Russia',
 'Central_Asia',
 'Middle_East',
 'China',
 'Korean_Japan',
 'South_Asia',
 'Southeast_Asia',
 'Oceania',
 'AgriWaste',
 'BioBurBiof',
 'Fossil',
 'OtherNatural',
 'Wetlands']

# Save regional stats
To be read in `index.html` in `TD_regionStats` dictionary.

In [18]:
import json

o=[]
for region in sources:
    # max, mean, min
    r_max=df_TD_piv.loc['SumSources'][region][0]
    r_mean=df_TD_piv.loc['SumSources'][region][1]
    r_min=df_TD_piv.loc['SumSources'][region][2]
    o.append({"sourceName": region,"mean":r_mean, "min":r_min, "max":r_max})
    
print(o)

[{'sourceName': 'USA', 'mean': 47, 'min': 34, 'max': 62}, {'sourceName': 'Canada', 'mean': 20, 'min': 13, 'max': 30}, {'sourceName': 'Central_America', 'mean': 13, 'min': 9, 'max': 28}, {'sourceName': 'Northern_South_America', 'mean': 20, 'min': 14, 'max': 27}, {'sourceName': 'Brazil', 'mean': 60, 'min': 38, 'max': 78}, {'sourceName': 'Southwest_South_America', 'mean': 26, 'min': 14, 'max': 35}, {'sourceName': 'Europe', 'mean': 31, 'min': 19, 'max': 41}, {'sourceName': 'Northern_Africa', 'mean': 26, 'min': 9, 'max': 34}, {'sourceName': 'Equatorial_Africa', 'mean': 44, 'min': 31, 'max': 60}, {'sourceName': 'Southern_Africa', 'mean': 18, 'min': 12, 'max': 24}, {'sourceName': 'Russia', 'mean': 34, 'min': 17, 'max': 47}, {'sourceName': 'Central_Asia', 'mean': 10, 'min': 7, 'max': 15}, {'sourceName': 'Middle_East', 'mean': 23, 'min': 15, 'max': 31}, {'sourceName': 'China', 'mean': 55, 'min': 43, 'max': 70}, {'sourceName': 'Korean_Japan', 'mean': 4, 'min': 3, 'max': 5}, {'sourceName': 'South_Asia', 'mean': 56, 'min': 26, 'max': 73}, {'sourceName': 'Southeast_Asia', 'mean': 59, 'min': 46, 'max': 67}, {'sourceName': 'Oceania', 'mean': 12, 'min': 8, 'max': 24}]

In [19]:
df_TD_piv.loc['SumSources']['USA']

stats
max     62
mean    47
min     34
Name: SumSources, dtype: int64

# Save to json

In [20]:
#Write json file for Sankey, MEAN VALUES ONLY

file = open(mean_name, 'w')

file.write('{\n')
file.write('"nodes": [\n')
for node in nodes:
    file.write('{"name": "%s"},\n' %(node))
# remove last comma
file.seek(0, os.SEEK_END)              # seek to end of file; f.seek(0, 2) is legal
file.seek(file.tell() - 2, os.SEEK_SET)   # go backwards 3 bytes
file.truncate()
file.write('\n],\n')

file.write('"links": [\n')

for source in sources:
    print(source)
    for target in targets:
        print(target)
        value = df_TD_piv[source].loc[target]['mean']
        if value != -99:
            if value != 0:
                print(value)
                file.write('{"source": "%s", "target": "%s", "value": "%.2f"},\n' %(source, target, float(value)))

# remove last comma           
file.seek(0, os.SEEK_END)              # seek to end of file; f.seek(0, 2) is legal
file.seek(file.tell() - 2, os.SEEK_SET)   # go backwards 3 bytes  
file.truncate()
file.write('\n]\n')
file.write('}\n')

file.close()

USA
AgriWaste
19
BioBurBiof
1
Fossil
12
OtherNatural
2
Wetlands
14
Canada
AgriWaste
3
BioBurBiof
1
Fossil
2
OtherNatural
1
Wetlands
13
Central_America
AgriWaste
7
BioBurBiof
1
Fossil
2
OtherNatural
1
Wetlands
3
Northern_South_America
AgriWaste
4
BioBurBiof
Fossil
3
OtherNatural
1
Wetlands
10
Brazil
AgriWaste
19
BioBurBiof
2
Fossil
2
OtherNatural
3
Wetlands
34
Southwest_South_America
AgriWaste
8
BioBurBiof
1
Fossil
2
OtherNatural
1
Wetlands
14
Europe
AgriWaste
18
BioBurBiof
1
Fossil
7
OtherNatural
2
Wetlands
3
Northern_Africa
AgriWaste
10
BioBurBiof
2
Fossil
5
OtherNatural
2
Wetlands
7
Equatorial_Africa
AgriWaste
10
BioBurBiof
5
Fossil
6
OtherNatural
3
Wetlands
20
Southern_Africa
AgriWaste
4
BioBurBiof
3
Fossil
3
OtherNatural
2
Wetlands
6
Russia
AgriWaste
5
BioBurBiof
2
Fossil
13
OtherNatural
2
Wetlands
12
Central_Asia
AgriWaste
4
BioBurBiof
Fossil
5
OtherNatural
1
Wetlands
Middle_East
AgriWaste
7
BioBurBiof
Fossil
13
OtherNatural
3
Wetlands
1
China
AgriWaste
26
BioBurBiof
4
Fossil
18
OtherNatural
1
Wetlands
5
Korean_Japan
AgriWaste
2
BioBurBiof
Fossil
1
OtherNatural
Wetlands
1
South_Asia
AgriWaste
36
BioBurBiof
2
Fossil
4
OtherNatural
1
Wetlands
12
Southeast_Asia
AgriWaste
21
BioBurBiof
5
Fossil
8
OtherNatural
3
Wetlands
22
Oceania
AgriWaste
5
BioBurBiof
1
Fossil
2
OtherNatural
2
Wetlands
2

In [21]:
#Write json file for Sankey, MIN VALUES ONLY

file = open(min_name, 'w')

file.write('{\n')
file.write('"nodes": [\n')
for node in nodes:
    file.write('{"name": "%s"},\n' %(node))
# remove last comma
file.seek(0, os.SEEK_END)              # seek to end of file; f.seek(0, 2) is legal
file.seek(file.tell() - 2, os.SEEK_SET)   # go backwards 3 bytes
file.truncate()
file.write('\n],\n')

file.write('"links": [\n')

for source in sources:
    print(source)
    for target in targets:
        print(target)
        value = df_TD_piv[source].loc[target]['min']
        if value != -99:
            if value != 0:
                print(value)
                file.write('{"source": "%s", "target": "%s", "value": "%.2f"},\n' %(source, target, float(value)))

# remove last comma           
file.seek(0, os.SEEK_END)              # seek to end of file; f.seek(0, 2) is legal
file.seek(file.tell() - 2, os.SEEK_SET)   # go backwards 3 bytes  
file.truncate()
file.write('\n]\n')
file.write('}\n')

file.close()

USA
AgriWaste
10
BioBurBiof
Fossil
9
OtherNatural
1
Wetlands
8
Canada
AgriWaste
2
BioBurBiof
1
Fossil
1
OtherNatural
Wetlands
6
Central_America
AgriWaste
5
BioBurBiof
Fossil
1
OtherNatural
1
Wetlands
2
Northern_South_America
AgriWaste
3
BioBurBiof
Fossil
2
OtherNatural
1
Wetlands
6
Brazil
AgriWaste
11
BioBurBiof
1
Fossil
1
OtherNatural
1
Wetlands
26
Southwest_South_America
AgriWaste
6
BioBurBiof
1
Fossil
1
OtherNatural
1
Wetlands
8
Europe
AgriWaste
13
BioBurBiof
1
Fossil
3
OtherNatural
1
Wetlands
2
Northern_Africa
AgriWaste
10
BioBurBiof
1
Fossil
3
OtherNatural
1
Wetlands
4
Equatorial_Africa
AgriWaste
6
BioBurBiof
4
Fossil
2
OtherNatural
1
Wetlands
15
Southern_Africa
AgriWaste
4
BioBurBiof
2
Fossil
2
OtherNatural
Wetlands
2
Russia
AgriWaste
4
BioBurBiof
2
Fossil
4
OtherNatural
1
Wetlands
9
Central_Asia
AgriWaste
3
BioBurBiof
Fossil
3
OtherNatural
Wetlands
Middle_East
AgriWaste
5
BioBurBiof
Fossil
3
OtherNatural
1
Wetlands
China
AgriWaste
23
BioBurBiof
Fossil
10
OtherNatural
1
Wetlands
2
Korean_Japan
AgriWaste
2
BioBurBiof
Fossil
OtherNatural
Wetlands
South_Asia
AgriWaste
24
BioBurBiof
2
Fossil
2
OtherNatural
1
Wetlands
6
Southeast_Asia
AgriWaste
20
BioBurBiof
4
Fossil
5
OtherNatural
1
Wetlands
15
Oceania
AgriWaste
3
BioBurBiof
Fossil
1
OtherNatural
1
Wetlands
1

In [22]:
#Write json file for Sankey, MAX VALUES ONLY

file = open(max_name, 'w')

file.write('{\n')
file.write('"nodes": [\n')
for node in nodes:
    file.write('{"name": "%s"},\n' %(node))
# remove last comma
file.seek(0, os.SEEK_END)              # seek to end of file; f.seek(0, 2) is legal
file.seek(file.tell() - 2, os.SEEK_SET)   # go backwards 3 bytes
file.truncate()
file.write('\n],\n')

file.write('"links": [\n')

for source in sources:
    print(source)
    for target in targets:
        print(target)
        value = df_TD_piv[source].loc[target]['max']
        if value != -99:
            if value != 0:
                print(value)
                file.write('{"source": "%s", "target": "%s", "value": "%.2f"},\n' %(source, target, float(value)))

# remove last comma           
file.seek(0, os.SEEK_END)              # seek to end of file; f.seek(0, 2) is legal
file.seek(file.tell() - 2, os.SEEK_SET)   # go backwards 3 bytes  
file.truncate()
file.write('\n]\n')
file.write('}\n')

file.close()

USA
AgriWaste
26
BioBurBiof
1
Fossil
18
OtherNatural
3
Wetlands
25
Canada
AgriWaste
4
BioBurBiof
1
Fossil
4
OtherNatural
2
Wetlands
20
Central_America
AgriWaste
7
BioBurBiof
1
Fossil
3
OtherNatural
1
Wetlands
3
Northern_South_America
AgriWaste
6
BioBurBiof
Fossil
5
OtherNatural
2
Wetlands
14
Brazil
AgriWaste
26
BioBurBiof
3
Fossil
2
OtherNatural
5
Wetlands
44
Southwest_South_America
AgriWaste
12
BioBurBiof
1
Fossil
3
OtherNatural
2
Wetlands
21
Europe
AgriWaste
26
BioBurBiof
1
Fossil
10
OtherNatural
3
Wetlands
8
Northern_Africa
AgriWaste
14
BioBurBiof
2
Fossil
9
OtherNatural
4
Wetlands
11
Equatorial_Africa
AgriWaste
12
BioBurBiof
6
Fossil
11
OtherNatural
7
Wetlands
27
Southern_Africa
AgriWaste
6
BioBurBiof
3
Fossil
5
OtherNatural
3
Wetlands
9
Russia
AgriWaste
7
BioBurBiof
3
Fossil
25
OtherNatural
3
Wetlands
16
Central_Asia
AgriWaste
5
BioBurBiof
Fossil
9
OtherNatural
1
Wetlands
Middle_East
AgriWaste
10
BioBurBiof
Fossil
20
OtherNatural
6
Wetlands
1
China
AgriWaste
35
BioBurBiof
5
Fossil
36
OtherNatural
1
Wetlands
9
Korean_Japan
AgriWaste
3
BioBurBiof
Fossil
1
OtherNatural
Wetlands
2
South_Asia
AgriWaste
51
BioBurBiof
3
Fossil
5
OtherNatural
2
Wetlands
18
Southeast_Asia
AgriWaste
27
BioBurBiof
7
Fossil
9
OtherNatural
4
Wetlands
33
Oceania
AgriWaste
7
BioBurBiof
1
Fossil
2
OtherNatural
3
Wetlands
4